stages:
  - test
  - analysis
  - deploy

# test
ut:
  stage: test
  tags: 
    - review_deploy
  script:
    - export http_proxy=http://172.20.1.246:12080/
    - export https_proxy=http://172.20.1.246:12080/
    - npm -g config set proxy http://172.20.1.246:12080
    - npm -g config set https-proxy http://172.20.1.246:12080
    - npm install
    - npm run test -- --coverage
  artifacts:
    paths:
    - coverage

## review
deploy_for_review:
  stage: test
  tags: 
    - review_deploy
  script:
    - echo "update family-t mss demo server contents"
    - mkdir -p /var/www/html/$CI_COMMIT_REF_SLUG
    - cp -rf ./* /var/www/html/$CI_COMMIT_REF_SLUG/
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://family-t.tkb.mss.co.jp/$CI_COMMIT_REF_SLUG/
  only:
    - branches
  except:
    - master
    
# release
deploy:
  stage: deploy
  script:
    - echo "update family-t demo server contents"
  only:
    - develop

# SonarQube analysis
SonarQube:
  stage: analysis
  tags: 
    - review_deploy
  variables:
    SONAR_HOST_URL: http://sonarqube.tkb.mss.co.jp/
    SONAR_TOKEN: ${SONARQUBE_TOKEN}
    SONAR_PROJECT_BASE_DIR: ${CI_PROJECT_DIR}
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    SOURCE_ENCODING: UTF-8
    LCOV_INFO: "__coverage__/lcov.info"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=family-t -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.sourceEncoding=${SOURCE_ENCODING} -Dsonar.javascript.lcov.reportPaths=${LCOV_INFO}
  allow_failure: true
  only:
    - develop
