# GitLabのパイプライン設定
# 要求：
# ブランチにプッシュされたとき
#  - 社内サーバを更新する（ブランチ名で公開する）
# developにマージされたとき(= developがプッシュされたとき)

stages:
  - build
  - deploy_review
  - analysis
  - deploy

# 社内ビルド
build:
  stage: build
  script:
    - echo "update family-t mss demo server contents"
    - mkdir -p /var/www/html/$CI_COMMIT_REF_SLUG
    - cp -rf ./* /var/www/html/$CI_COMMIT_REF_SLUG/

## レビュー
deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://family-t.tkb.mss.co.jp/$CI_COMMIT_REF_SLUG/
  only:
    - branches
  except:
    - master
    
# リリース
deploy:
  stage: deploy
  script:
    - echo "update family-t demo server contents"
  only:
    - develop

# 静的解析
analysis:
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_HOST_URL: http://sonarqube.tkb.mss.co.jp/
    SONAR_TOKEN: ${SONARQUBE_TOKEN}
    SONAR_PROJECT_BASE_DIR: ${CI_PROJECT_DIR}
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=family-t -Dsonar.host.url=${SONAR_HOST_URL}
  allow_failure: true
  only:
    - 65-ci-sonarqube-sonarqube
    # - develop
