# GitLabのパイプライン設定
# 要求：
# ブランチにプッシュされたとき
#  - 社内サーバを更新する（ブランチ名で公開する）
# developにマージされたとき(= developがプッシュされたとき)

# 社内ビルド
build:
  stage: build
  script:
    - echo "update family-t mss demo server contents"
    - mkdir -p /var/www/html/$CI_COMMIT_REF_SLUG
    - cp -rf ./* /var/www/html/$CI_COMMIT_REF_SLUG/

## レビュー
deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://family-t.tkb.mss.co.jp/$CI_COMMIT_REF_SLUG/
  only:
    - branches
  except:
    - master
    
# リリース
deploy:
  stage: deploy
  script:
    - echo "update family-t demo server contents"
  only:
    - develop
